ALTER TABLE USER_API_KEY
    ADD COLUMN SHARED_ALL_LIBRARIES boolean NOT NULL DEFAULT 1;

ALTER TABLE USER_API_KEY
    ADD COLUMN AGE_RESTRICTION integer;

ALTER TABLE USER_API_KEY
    ADD COLUMN AGE_RESTRICTION_ALLOW_ONLY boolean;

CREATE TABLE USER_API_KEY_ROLE
(
    API_KEY_ID varchar NOT NULL,
    ROLE       varchar NOT NULL,
    PRIMARY KEY (API_KEY_ID, ROLE),
    FOREIGN KEY (API_KEY_ID) REFERENCES USER_API_KEY (ID) ON DELETE CASCADE
);

CREATE TABLE USER_API_KEY_LIBRARY_SHARING
(
    API_KEY_ID varchar NOT NULL,
    LIBRARY_ID varchar NOT NULL,
    PRIMARY KEY (API_KEY_ID, LIBRARY_ID),
    FOREIGN KEY (API_KEY_ID) REFERENCES USER_API_KEY (ID) ON DELETE CASCADE,
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID)
);

CREATE TABLE USER_API_KEY_SHARING
(
    API_KEY_ID varchar  NOT NULL,
    ALLOW      boolean  NOT NULL,
    LABEL      varchar  NOT NULL,
    PRIMARY KEY (API_KEY_ID, ALLOW, LABEL),
    FOREIGN KEY (API_KEY_ID) REFERENCES USER_API_KEY (ID) ON DELETE CASCADE
);

CREATE INDEX idx__user_api_key_role__api_key_id
    ON USER_API_KEY_ROLE (API_KEY_ID);

CREATE INDEX idx__user_api_key_library_sharing__api_key_id
    ON USER_API_KEY_LIBRARY_SHARING (API_KEY_ID);

CREATE INDEX idx__user_api_key_sharing__api_key_id
    ON USER_API_KEY_SHARING (API_KEY_ID);

INSERT INTO USER_API_KEY_ROLE
SELECT ID, 'ADMIN'
FROM USER_API_KEY;

INSERT INTO USER_API_KEY_ROLE
SELECT ID, 'FILE_DOWNLOAD'
FROM USER_API_KEY;

INSERT INTO USER_API_KEY_ROLE
SELECT ID, 'PAGE_STREAMING'
FROM USER_API_KEY;

INSERT INTO USER_API_KEY_ROLE
SELECT ID, 'KOBO_SYNC'
FROM USER_API_KEY;

INSERT INTO USER_API_KEY_ROLE
SELECT ID, 'KOREADER_SYNC'
FROM USER_API_KEY;
